const listaPalabras = [
  'Alcoholimetro',  'mide la cantidad de alcohol',
  'Agente de transito', 'persona que ordena el transito',
  'Atropello','Acción de atropellar un vehículo a una persona o animal',
  'Colision vial', 'comprende el choque de uno o más vehículos en movimiento',
  'accidente vial', 'accidente que toma lugar en la vía pública',
  'Via publica', 'lugar por donde circula la gente',
  'Vehiculo', 'medio de transporte comun',
  'Peaton', 'Persona que va a pie por una vía pública',
  'Ruta', 'camino establecido o previsto para un viaje',
  'señales de transito', 'signos usados en la vía pública para informar​',
  'conductor', 'persona que maneja dentro del auto',
  'semaforo', 'indica quién debe pasar o detenerse y tiene tres colores',
  'siniestro vial', 'suceso en la via publica con una persona herida o muerta',
  'airbag','objeto de seguridad en el auto que consiste en una bolsa',
  'autopista','vía de circulación',
  'cedula verde', 'documento que acredita que un vehículo puede circular en la vía pública',
  'cinturon de seguridad', 'impide ser despedido del vehículo y otorga mayor seguridad',
  'cinta reflectiva','cinta que refleja la luz, se suele usar en los chalecos de seguridad',
  'loma de burro','se construye para limitar la velocidad del vehiculo',
  'Ambulancia','vehículo especialmente adaptado para el transporte de heridos',
  'Casco','objeto que se utiliza en la cabeza para evitar heridas y golpes',
  'freno de mano','sistema que inmoviliza el vehicul cuando esta detenido',
  'freno de mano','sistema que inmoviliza el vehiculo cuando esta detenido',
  'vidrio polarizado','material usado para reducir los rayos uv',

];
